INSERT INTO `chineseIdioms`.`user`(`username`, `password`, `process`) VALUES ('superxc', 'a2854d99bb0d12cd0bae0e536a0084a2', 4);
INSERT INTO `chineseIdioms`.`user`(`username`, `password`, `process`) VALUES ('yujialee', '9d7e5b85f7f4b0b650ac07726142cad9', 0);

INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (1, '风尘仆仆', '风尘：指行旅，含有辛苦之意；仆仆：行路劳累的样子。 形容旅途奔波，忙碌劳累。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (1, '步步高升', '步步：表示距离很短；高升：往上升。指职位不断上升。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (1, '人才济济', '济济：众多的样子。 形容有才能的人很多。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (1, '生机勃勃', '形容自然界充满生命力，或社会生活活跃。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (1, '千里迢迢', '迢迢：遥远。形容路途遥远。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (2, '恭喜发财', '喜：喜悦的心。用恭敬的心和喜悦的心去祝福他人发财致富。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (2, '三阳开泰', '称爻连的为阳卦，断的为阴爻，正月为泰卦，三阳生于下；冬去春来，阴消阳长，有吉亨之象。常用以称颂岁首或寓意吉祥。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (2, '侃侃而谈', '理直气壮，从容不迫。理直气壮、从容不迫地说话。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (2, '班门弄斧', '在鲁班门前舞弄斧子。 比喻在行家面前卖弄本领，不自量力。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (2, '背水一战', '背水：背向水，表示没有退路。 比喻与敌人决一死战。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (3, '格格不入', '格格：阻碍，隔阂。形容彼此不协调，不相容。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (3, '斤斤计较', '斤斤：形容明察，引伸为琐碎细小。只对无关紧要的事过分计较。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (3, '津津有味', '津津：兴趣浓厚的样子。指吃得很有味道或谈得很有兴趣。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (3, '依依不舍', '依依：依恋的样子；舍：放弃。形容舍不得离开。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (3, '默默无闻', '无声无息，没人知道。 指没有什么名声。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (4, '舍我其谁', '舍：除了。 除了我还有哪一个？形容人敢于担当，遇有该做的事，决不退让。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (4, '不吐不快', '吐：倾诉；快：痛快。不说出来就不痛快');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (4, '飞蛾扑火', '飞蛾扑到火上，比喻自取灭亡。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (4, '水滴石穿', '水不停地滴，石头也能被滴穿。 比喻只要有恒心，不断努力，事情就一定能成功。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (4, '海阔天空', '像大海一样辽阔，像天空一样无边无际。形容大自然的广阔。比喻言谈议论等漫无边际，没有中心。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (5, '念念不忘', '念念：时刻思念着。形容牢记于心，时刻不忘。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (5, '滔滔不绝', '滔滔：形容流水不断。像流水那样毫不间断。指话很多，说起来没个完。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (5, '源源不断', '形容接连不断。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (5, '白日做梦', '大白天做梦。 比喻根本不能实现的梦想。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (5, '别出心裁', '别：另外；心裁：心中的设计、筹划。 另有一种构思或设计。指想出的办法与众不同。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (6, '自怨自艾', '怨：怨恨，悔恨；艾：割草，比喻改正错误。原意是悔恨自己的错误，自己改正。现在只指悔恨自己的错误。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (6, '物竞天择', '物竞：生物的生存竞争；天择：自然选择。生物相互竞争，能适应者生存下来。原指生物进化的一般规律，后也用于人类社会的发展。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (6, '情非得已', '指情况出于不得已。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (6, '风驰电掣', '驰：奔跑；掣：闪过。 形容非常迅速，像风吹电闪一样。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (6, '满腹经纶', '经纶：整理丝缕，引伸为人的才学、本领。形容人极有才干和智谋。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (6, '兵临城下', '敌军已来到自己的城墙下面。比喻情势十分危急。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (7, '囫囵吞枣', '囫囵：整个儿。把枣整个咽下去，不加咀嚼，不辨滋味。比喻对事物不加分析思考。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (7, '滴水成冰', '水滴下去就结成冰。 形容天气十分寒冷。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (7, '见风使舵', '看风向转发动舵柄。比喻看势头或看别人的眼色行事。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (7, '牛鬼蛇神', '牛头的鬼，蛇身的神。原形容虚幻怪诞。后比喻社会上形形色色的坏人。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (7, '插翅难逃', '插上翅膀也难逃走。比喻陷入困境，怎么也逃不了。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (7, '称心如意', '形容心满意足，事情的发展完全符合心意。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (8, '事半功倍', '指做事得法，因而费力小，收效大。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (8, '阿鼻地狱', '阿鼻：梵语的译音，意译为“无间”，即痛苦无有间断之意。 常用来比喻黑暗的社会和严酷的牢狱。又比喻无法摆脱的极其痛苦的境地。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (8, '天下无双', '天下找不出第二个。 形容出类拔萃，独一无二。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (8, '长生不死', '生命长存，永不死亡。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (8, '运筹帷幄', '筹：计谋、谋划；帷幄：古代军中帐幕。指拟定作战策略。引申为筹划、指挥。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (8, '琳琅满目', '琳琅：精美的玉石。满眼都是珍贵的东西。形容美好的事物很多。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (9, '卧虎藏龙', '指隐藏着未被发现的人才，也指隐藏不露的人才。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (9, '杯水车薪', '用一杯水去救一车着了火的柴草。比喻力量太小，解决不了问题。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (9, '逝者如斯', '用以形容光阴如流水一去不返。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (9, '有的放失', '的：箭靶子；矢：箭。 放箭要对准靶子。比喻说话做事有针对性。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (9, '同仇敌忾', '同仇：共同对敌；敌：对抗，抵拒；忾：愤怒。指全体一致痛恨敌人。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (9, '风卷残云', '大风把残云卷走。 比喻一下子把残存的东西一扫而光。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (10, '充耳不闻', '充：塞住。塞住耳朵不听。形容有意不听别人的意见。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (10, '如坐针毡', '像坐在插着针的毡子上。 形容心神不定，坐立不安。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (10, '曲径通幽', '曲：弯曲；径：小路；幽：指深远僻静之处。弯曲的小路，通到幽深僻静的地方。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (10, '手到病除', '刚动手治疗，病就除去了。形容医术高明。也比喻工作做得很好，解决问题迅速。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (10, '喜从天降', '喜事从天上掉下来。比喻突然遇到意想不到的喜事。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (10, '妙语如珠', '指诗文中警句妙语很多。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '矫枉过正', '矫：扭转；枉：弯曲。把弯的东西扳正，又歪到了另一边。比喻纠正错误超过了应有的限度。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '朝秦幕楚', '战国时期，秦楚两个诸侯大国相互对立，经常作战。有的诸侯小国为了自身的利益与安全，时而倾向秦，时而倾向楚。比喻人反复无常。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '绘声绘影', '形容叙述或描写生动逼真。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '睚眦必报', '睚眦：发怒时瞪眼睛，借指极小的仇恨。像瞪一下眼睛那样极小的怨仇也要报复。比喻心胸极狭窄。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '姗姗来迟', '姗姗：形容走得缓慢从容。慢腾腾地来晚了。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '哭笑不得', '哭也不好，笑也不好。 形容很尴尬。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (11, '相亲相爱', '形容关系密切，感情深厚。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '重见天日', '重新看到了天和太阳。比喻脱离黑暗，重见光明。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '孜孜不倦', '孜孜：勤勉，不懈怠。指工作或学习勤奋不知疲倦。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '集腋成裘', '腋：腋下，指狐狸腋下的皮毛；裘：皮衣。狐狸腋下的皮虽很小，但聚集起来就能制一件皮袍。比喻积少成多。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '金玉良缘', '原指符合封建秩序的姻缘。 后泛指美好的姻缘。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '风月无边', '极言风景之佳胜。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '掌上明珠', '比喻接受父母疼爱的儿女，特指女儿。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (12, '入木三分', '相传王羲之在木板上写字，木工刻时，发现字迹透入木板三分深。 形容书法极有笔力。现多比喻分析问题很深刻。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '皆大欢喜', '皆：都。人人都高兴满意。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '沆瀣一气', '沆瀣：指唐时的崔沆、崔瀣。比喻臭味相投的人结合在一起。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '咫尺天涯', '咫：古代长度单位，周制八寸，合今市尺六寸二分二厘；咫尺：比喻距离很近。比喻距离虽近，但很难相见，像是远在天边一样。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '逍遥法外', '逍遥：优游自得的样子。指犯法的人没有受到法律制裁，仍然自由自在。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '生财有道', '原指生财有个大原则，后指搞钱很有办法。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '兄弟阋墙', '阋：争斗。兄弟之间的纠纷，也比喻内部争斗。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (13, '手到病除', '刚动手治疗，病就除去了。形容医术高明。也比喻工作做得很好，解决问题迅速。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '贼眉鼠眼', '形容神情鬼鬼祟祟。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '肝胆相照', '肝胆：比喻真心诚意。比喻以真心相见。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '百年好合', '夫妻永远和好之意。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '玄衣督邮', '龟的别名。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '二竖为灾', '竖：小子；二竖：指病魔。比喻疾病缠身');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '未雨绸缪', '绸缪：紧密缠缚。天还没有下雨，先把门窗绑牢。比喻事先做好准备工作。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (14, '女娲补天', '神话故事，伏羲的妹妹女娲炼五色石补天。形容改造天地的雄伟气魄和大无畏的斗争精神。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '欲擒故纵', '擒：捉；纵：放。 故意先放开他，使他放松戒备，充分暴露，然后再把他捉住。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '筚路蓝缕', '筚路：柴车；蓝缕：破衣服。驾着简陋的车，穿着破烂的衣服去开辟山林。形容创业的艰苦。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '讹言谎语', '讹言：谣言。造谣说谎话、讹言：诈伪的话；谎语：不真实的话。指造谣说谎。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '马首是瞻', '瞻：往前或向上看。 看着我马头的方向，决定进退。比喻追随某人行动。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '衣香鬓影', '形容妇女的衣着穿戴十分华丽（多指人多的场合）。 借指妇女。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '旗鼓相当', '比喻双方力量不相上下。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (15, '金戈铁马', '戈闪耀着金光，马配备了铁甲。 比喻战争。也形容战士持枪驰马的雄姿。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '耳闻目览', '亲自听见和亲眼看见的。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '毛遂自荐', '毛遂自我推荐。比喻自告奋勇，自己推荐自己担任某项工作。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '囊萤映雪', '原是车胤用口袋装萤火虫来照书本，孙康利用雪的反光勤奋苦学的故事。后形容刻苦攻读。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '熏腐之余', '熏腐：阉割。 腐刑之后。指宦官。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '阿尊事贵', '逢迎侍奉位高权重的权贵。 《汉书·卷三十六·楚元王刘交传》：“以不能阿尊事贵，孤特寡助，抑厌遂退，卒不克明。”');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '患得患失', '患：忧患，担心。担心得不到，得到了又担心失掉。形容对个人得失看得很重。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '耳濡目击', '见“ 耳濡目染 ”。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (16, '点石成金', '比喻修改文章时稍稍改动原来的文字，就使它变得很出色。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '墨客骚人', '墨客：文人；骚人：诗人。泛指文人。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '饿虎见羊', '饥饿的老虎见到一只羊羔。 比喻迅猛贪婪。、饥饿的老虎见到一只羊羔。比喻迅猛贪婪');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '分庭抗礼', '庭：庭院；抗礼：平等行礼。 原指宾主相见，分站在庭的两边，相对行礼。现比喻平起平坐，彼此对等的关系。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '你争我夺', '指相互争夺');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '无动于衷', '衷：内心。 心里一点儿也没有触动。指对应该关心、注意的事情毫不关心，置之不理。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '恩断义绝', '恩：恩情；义：情义。感情破裂。多指夫妻离异。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '压寨夫人', '旧小说、戏曲中指山寨头领的妻子');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (17, '买椟还珠', '椟：木匣；珠：珍珠。买下木匣，退还了珍珠。比喻没有眼力，取舍不当。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '耳热眼花', '眼睛发花，耳朵发热。形容饮酒微有醉意，精神兴奋的感觉');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '络绎不绝', '形容行人车马来来往往，接连不断。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '望穿秋水', '秋水：比喻人的眼睛。眼睛都望穿了。形容对远地亲友的殷切盼望。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '养生之道', '指修养身心，以期保健延年的方法。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '恩恩怨怨', '指人的感恩之情与仇怨之情');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '光杆司令', '指没有兵，只靠自己一个人。形容只剩下孤单一人，');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '二仙传道', '两位神仙一起传授道法。 比喻两从秘密地配合做成某件事。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (18, '喔咿儒睨', '儒睨：强笑的样子。形容老着脸皮，强作欢颜、儒睨：强笑的样子。形容老着脸皮，强作欢颜。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '欲盖弥彰', '指想掩盖坏事的真相，结果反而更明显地暴露出来。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '绿树成荫', '形容树木枝叶茂密，遮蔽了阳光。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '耳不离腮', '接近，亲密');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '唯我独尊', '原为佛家语，称颂释迦牟尼最高贵、最伟大。 现指认为只有自己最了不起。形容极端自高自大。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '万丈高楼', '比喻事物从无到有。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '雷霆万钧', '霆：急雷；钧：古代重量单位，三十斤为一钧。 形容威力极大，无法阻挡。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '承上启下', '承接上面的，引起下面的。 多用在写文章方面。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (19, '程门立雪', '旧指学生恭敬受教。比喻尊师。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '目无全牛', '全牛：整个一头牛。眼中没有完整的牛，只有牛的筋骨结构。比喻技术熟练到了得心应手的境地。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '走漏风声', '泄漏机密或消息');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '耳聋眼瞎', '指因突然遭到强烈刺激而耳朵变聋,眼睛变瞎');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '糊涂到顶', '人头脑十分不清楚或不明事理。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '空头人情', '虚假的情意 ');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '九九归一', '归根到底。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '门庭若市', '庭：院子；若：像；市：集市。 门前和院子里人很多，像市场一样。原形容进谏的人很多。现形容来的人很多，非常热闹。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (20, '妄自菲薄', '形容过分看轻自己，形容自卑心理 ，自轻自贱。指对自己的能力等没有自信，不相信自己可以完成。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '温人之周', '比喻对的事情要坚持到底。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '沐猴而冠', '沐猴：猕猴；冠：戴帽子。 猴子穿衣戴帽，究竟不是真人。比喻虚有其表，形同傀儡。常用来讽刺投靠恶势力窃据权位的人。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '亲上加亲', '亲上加亲意思是原是亲戚,又再结姻亲');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '绝处逢生', '绝处：死路。形容在最危险的时候得到生路。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '亦步亦趋', '原意是说，你慢走我也慢走，你快走我也快走，你跑我也跑。比喻由于缺乏主张，或为了讨好，事事模仿或追随别人。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '无的放矢', '的：靶心；矢：箭。没有目标乱射箭。比喻说话做事没有明确目的，或不切合实际。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '目空四海', '眼看四海之内皆空。 比喻目中无人、狂妄或自负之甚');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '分道扬镳', '分路而行。比喻目标不同，各走各的路或各干各的事。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (21, '聊胜于无', '聊：略微。比没有要好一点。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '江郎才尽', '江郎：指南朝江淹。原指江淹少有文名，晚年诗文无佳句。比喻才情减退。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '横行霸道', '横行：行动蛮横仗势做坏事；霸道：蛮不讲理。 依仗权势为非作歹。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '争分夺秒', '一分一秒也不放过。形容充分利用时间。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '连滚带爬', '形容害怕得慌乱逃走的样子。、形容害怕得慌乱逃走的样子');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '无影无踪', '踪：踪迹。没有一点踪影。形容完全消失，不知去向。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '阿谀顺旨', '逢迎谄媚，顺从别人意旨。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '校人烹鱼', ' 用花言巧语编造的谎言,常常使那些不了解实际情况的人上当。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '露水夫妻', '指暂时结合的非正式夫妻；亦指不正当的男女关系。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (22, '中流砥柱', '就像屹立在黄河急流中的砥柱山一样。比喻坚强独立的人能在动荡艰难的环境中起支柱作用');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '扼臂啮指', '扼：用力掐；啮：咬。掐胳膊，咬手指。形容母子心灵相互感应。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '一年一回', '指一年一次');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '旬月之间', '旬：十天。十天到一个月之间');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '光棍一条', '光棍：没有配偶的人。指孤身一人');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '龙虎风云', '①比喻英雄豪杰际遇得时。②指君臣遇合。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '铁树开花', '铁树：也叫苏铁，常绿乔木，不常开花。比喻事情非常罕见或极难实现。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '轻重九府', '掌管财政的九个官署，即大府、王府、内府、外府、泉府、天府、职内、职金、职币。轻重，指钱币');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '二人同心', '比喻只要两个人齐心协力，就会无往不胜。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (23, '夜郎自大', '夜郎：汉代西南地区的一个小国。比喻人无知而又狂妄自大。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '鬼话连篇', '鬼话：不真实的话。连篇：一篇接一篇。满口说的全是蒙骗人的胡言乱语。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '耳边之风', '耳旁之风，一吹而过。比喻不重视，听了不放在心上的话');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '眉目不清', '眉目：条理。事物条理不清或文章没有条理、眉目：指事情的条理、状况。比喻事情的状况不清楚。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '悬梁刺股：形容刻苦学', '');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '敲山震虎', '指故意示警，使人震动。 同“敲山振虎”。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '全力以赴', '赴：前往。把全部力量都投入进去。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '钟灵毓秀', '钟：凝聚，集中；毓：养育。 凝聚了天地间的灵气，孕育着优秀的人物。指山川秀美，人才辈出。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '直来直去', '1.指来去途中不绕道、不停留 2.说话、做事不绕弯子');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (24, '走回头路', '1.比喻倒退，或按已经不合时宜的老规矩办事 2.比喻顺原路倒退回去');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '不一而足', '足：充足。 指同类的事物不只一个而是很多，无法列举齐全。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '淋漓尽致', '淋漓：形容湿淋淋往下滴，比喻尽情，酣畅；尽致：达到极点。 形容文章或说话表达得非常充分、透彻，或非常痛快。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '原宪桑枢', '安贫乐道。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '出水芙蓉', '芙蓉：荷花。刚开放的荷花。比喻诗文清新不俗。也形容天然艳丽的女子。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '恩高义厚', '恩德情义极为深重');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '瓯饭瓢饮', '瓯：小盆。用小盆吃饭，用瓢喝水。形容穷苦的生活。、瓯：小盆。用小盆吃饭，用瓢喝水。形容穷苦的生活');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '风声鹤唳', '唳：鹤叫声。 形容惊慌失措，或自相惊忧。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '和光同尘', '和、同：混合。 和光：混合各种光彩；同尘：与尘俗相同。指不露锋芒，与世无争的消极处世态度。也比喻同流合污。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (25, '水漫金山', '神话故事。金山，在江苏省镇江市。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '事出意外', '指出乎人的意料之外的事情。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '围魏救赵', '原指战国时齐军用围攻魏国的方法，迫使魏国撤回攻赵部队而使赵国得救。 后指袭击敌人后方的据点以迫使进攻之敌撤退的战术。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '恶衣薄食', '衣：衣服；薄：淡薄；食：事物。形容生活清苦、衣：衣服；薄：淡薄；食：事物。形容生活清苦。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '取舍两难', '采用或舍弃都能决定。指难以抉择、采用或舍弃都能决定。指难以抉择。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '折臂三公', '晋代的羊枯，曾坠马折断手臂，官至三公。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '厚德载物', '旧指道德高尚者能承担重大任务。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '图穷匕见', '图：地图；穷：尽；见：现。 比喻事情发展到最后，真相或本意显露了出来。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '三从四德', '封建礼教束缚妇女的道德标准之一。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '干干脆脆', '痛痛快快、痛痛快快，干净利索。 、干净利索');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (26, '望其项背', '项：颈的后部。望见他的颈项和后背。比喻赶得上。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '亡羊补牢', '亡：逃亡，丢失；牢：关牲口的圈。 羊逃跑了再去修补羊圈，还不算晚。比喻出了问题以后想办法补救，可以防止继续受损失。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '随遇而安', '随：顺从；遇：遭遇。 指能顺应环境，在任何境遇中都能满足。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '抛砖引玉', '抛出砖去，引回玉来。比喻用自己不成熟的意见或作品引出别人更好的意见或好作品。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '罗缕纪存', '罗缕，详细。纪存，纪录保存');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '惊天动地', '惊：惊动；动：震撼。 使天地惊动。形容某个事件的声势或意义极大。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '残羹冷炙', '指吃剩的饭菜。也比喻别人施舍的东西。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '冠冕堂皇', '冠冕：古代帝王、官吏的帽子；堂皇：很有气派的样子。 形容外表庄严或正大的样子。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '阿旨顺情', '阿：曲从；旨：圣旨。曲意逢迎');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '卧冰求鲤', '卧在冰上以求得鲤鱼。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (27, '举一反三', '反：类推。比喻从一件事情类推而知道其他许多事情。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '过犹不及', '过：过分；犹：像；不及：达不到。 事情做得过头，就跟做得不够一样，都是不合适的。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '离题太远', '离开主题很远，不着边际。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '千古奇冤', '千百年来少有的冤案。周恩来 《为＜新华日报＞题词》:“千古奇冤，江南一 叶 ，同室操戈，相煎何急！”');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '烟雨蒙蒙', '一般是形容江南的雨才用这个词，雨丝很细密，有如雾似烟的那种感觉。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '名副其实', '名声或名义和实际相符。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '春暖花开', '春天气候温暖，百花盛开，景色优美。比喻游览、观赏的大好时机。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '历历在目', '历历：清楚，分明的样子。指远方的景物看得清清楚楚，或过去的事情清清楚楚地重现在眼前。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '无本生意', '没有成本的买卖。、没有成本的买卖');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '根深蒂固', '比喻基础深厚，不容易动摇。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (28, '金屋藏娇', '娇：原指汉武帝刘彻的表妹陈阿娇。 汉武帝幼小时喜爱阿娇，并说要让她住在金屋里。指以华丽的房屋让所爱的妻妾居住。也指取妾。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '赶尽杀绝', '驱除干净，彻底消灭。比喻残忍狠毒，不留余地。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '回心转意', '心、意：心思；回、转：掉转。 重新考虑，改变原来的想法和态度。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '服服帖帖', '温顺地或谦恭地服从跟随');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '杀生与夺', '指生死赏罚的大权');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '学富五车', '五车：指五车书。形容读书多，学识丰富。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '惊涛骇浪', '涛：大波浪；骇：使惊怕。汹涌吓人的浪涛。比喻险恶的环境或尖锐激烈的斗争。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '炙手可热', '手摸上去感到热得烫人。 比喻权势大，气焰盛，使人不敢接近。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '来历不明', '来历：由来。 人或事物的来历与经过不清楚。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '半截入土', '截：段。 半段身子埋入土内。比喻人在世不久了。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (29, '一家之主', '家庭的当家人');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '按图索骥', '索：找；骥：良马。按照画像去寻求好马。比喻墨守成规办事；也比喻按照线索去寻求。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '王侯将相', '泛指封建社会中位尊、禄厚、权重、势大的贵族。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '横扫千军', '横扫：扫荡、扫除。把大量敌军象扫地似地一阵子扫除掉。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '万箭穿心', '犹万箭攒心。形容万分伤痛。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '喜闻乐见', '喜欢听，乐意看。指很受欢迎。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '苟延残喘', '苟：暂且，勉强；延：延续；残喘：临死前的喘息。勉强延续临死前的喘息。比喻暂时勉强维持生存。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '三角恋爱', '指一个人和两个异性同时恋爱的不正常的关系');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '鳞次栉比', '栉：梳篦的总称。像鱼鳞和梳子齿那样有次序地排列着。多用来形容房屋或船只等排列得很密很整齐。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '插科打诨', '科：指古典戏曲中的表情和动作；诨：诙谐逗趣的话。戏曲、曲艺演员在表演中穿插进去的引人发笑的动作或语言。');
INSERT INTO `chineseIdioms`.`idiom`(`groupId`, `value`, `description`) VALUES (30, '沧海桑田', '桑田：农田。 大海变成桑田，桑田变成大海。比喻世事变化很大。');